# Generated by Django 5.2.3 on 2025-07-07 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("keywords", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="aaecphotos"),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="aaecphotos"),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
