# Generated by Django 5.2.3 on 2025-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
