# Generated by Django 5.2.3 on 2025-08-05 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("cars", "0002_alter_carservicerecord_car"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="service_record",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="tax_percent",
        ),
        migrations.AddField(
            model_name="bill",
            name="amount_remaining",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="car",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="cars.car",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="entered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="total_inventory_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bill",
            name="total_service_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bill",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="BillLineItem",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
