# Generated by Django 5.2.3 on 2025-08-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_archivedinventoryusage_archivedservicerecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="archivedinventoryusage",
            old_name="item_name",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="archivedinventoryusage",
            old_name="updated_at",
            new_name="used_at",
        ),
        migrations.CreateModel(
            name="ArchivedServiceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("service_description", models.TextField(blank=True, null=True)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("performed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paid_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_services",
                        to="billing.paidbill",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ArchivedServiceRecord",
        ),
    ]
