# Generated by Django 5.2.3 on 2025-06-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "car_image",
                    models.ImageField(blank=True, null=True, upload_to="car_images/"),
                ),
                ("owner_name", models.CharField(max_length=100)),
                ("owner_contact", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="JobEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manual_book_number", models.CharField(max_length=50)),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_entries",
                        to="cars.car",
                    ),
                ),
            ],
        ),
    ]
