# Generated by Django 5.2.3 on 2025-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_service_carservicerecord_inventoryusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryusage",
            name="used_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
