# Generated by Django 5.2.3 on 2025-07-22 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_carservicerecord_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="car",
            name="kms_reading",
            field=models.CharField(blank=True, default="0", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="owner_email",
            field=models.EmailField(
                blank=True, default="owner@email.com", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="registration_number",
            field=models.CharField(blank=True, default="NA", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="service_type",
            field=models.CharField(
                choices=[("free", "Free"), ("paid", "Paid")],
                default="paid",
                max_length=10,
            ),
        ),
    ]
