# Generated by Django 5.2.3 on 2025-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_car_created_at_car_kms_reading_car_owner_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
